feat(dev): add github icon on top of demo.tutorialkit.dev TopBar
stackblitz/tutorialkit pull request #338
Opened 2024-09-19 16:52 UTC by Charan167

- Add Github icon link on top of demo.tutorialkit.dev TopBar

https://github.com/user-attachments/assets/2b2aaa63-f491-4e0b-9e73-204e1e31d36f

2024-09-20 06:54 UTC, AriPerkkio requested changes
Great work @Charan167!

This PR should only make changes to `docs/demo/**` files. Couple of changes below:

- move the `Github.tsx` to `docs/demo/src/components/Github.tsx`
- add `docs/demo/src/components/TopBar.tsx` with following:
  ```astro
  ---
  import Github from "./Github";
  ---

  <nav
    class="bg-tk-elements-topBar-backgroundColor transition-theme border-b border-tk-elements-app-borderColor flex max-w-full items-center p-3 px-4 min-h-[56px]"
  >
    <div class="flex flex-1">
      <slot name="logo" />
    </div>
    <div class="mr-2">
      <slot name="open-in-stackblitz-link" />
    </div>

    <Github />

    <div>
      <slot name="theme-switch" />
    </div>
    <div>
      <slot name="login-button" />
    </div>
  </nav>
  ```
- define `components.TopBar` in `docs/demo/astro.config.ts` like this: https://github.com/AriPerkkio/tutorial-vite-plugin/pull/7/files#diff-baf06eda15601b59413c77e1f18884403033204061e6c9408cd9a3bb5bc6e586R10-R12

Now you should see the icon when running `pnpm dev` in `docs/demo` directory.

2024-09-20 09:51 UTC, Charan167 reviewed
- Moved Github.tsx to docs/demo/src/components/Github.tsx
- Defined components.TopBar in docs/demo/astro.config.ts

2024-09-20 10:39 UTC, AriPerkkio commented on packages/astro/src/default/components/TopBar.astro
> +  </div>
```suggestion
```

2024-09-20 10:58 UTC, AriPerkkio approved these changes
Looks good, thanks @Charan167! 🎉 

If you want to work more on improving the demo site, good next task would be to add `editPageLink` there: https://tutorialkit.dev/reference/configuration/#editpagelink.

2024-09-20 10:59 UTC, merged

2024-09-20 16:27 UTC, Charan167 commented
@AriPerkkio Sure!!! I've made the changes by adding editpagelink in the lesson’s frontmatter block. Please confirm if it's supposed to work like this.

https://github.com/user-attachments/assets/87caf5f2-0c14-4c91-8562-015f6e5a93b8

2024-09-21 09:41 UTC, AriPerkkio commented
Yes, that's the intention. But it looks like the link is not working. Maybe the URL is not correct?

Here's Tutorial that has correctly working edit page link: https://tutorial-vite-plugin.pages.dev

2024-09-21 14:21 UTC, Charan167 commented
@AriPerkkio Thank you for your help!!! I missed the demo part again 😅. I've made the necessary changes and created a PR.