docs: add docs for file imports
stackblitz/tutorialkit pull request #368
Opened 2024-10-10 01:13 UTC by kevinzunigacuellar

**Description**

- Closes #250
- Adds docs for file imports using shortcuts `file` and `solution`

2024-10-10 06:30 UTC, AriPerkkio requested changes
Thanks for the PR! :raised_hands:

This is good a start. For the #250 I think we want to have documentation for all supported markdown syntax. It should have links to [Astro](https://docs.astro.build/en/guides/content/) and [`expressive-code`](https://expressive-code.com/key-features/syntax-highlighting/), and probably some small examples from each. Also the [Callouts](https://tutorialkit.dev/reference/theming/#callouts).

The structure could be something like:

```md
// creating-content.mdx

## Markdown support
...

### Displaying code
<some examples showing how to select language for syntax highlight and highglight specific lines. Add links to asto & expressive-code.>

### Importing files
<the guide this pr already has>

### Callouts
<examples and description of callouts>
```

@Nemikolh & @sulco any thoughts?

2024-10-10 07:02 UTC, Nemikolh commented
@AriPerkkio, I agree with your proposed structure! Long term we could even have the `# Markdown support` section describes everything that's possible but right now if it shows the most commonly used things and link to `expressive-code` that would be a great start :raised_hands:

2024-10-10 09:52 UTC, kevinzunigacuellar commented
Thanks for the review and clarification. I wasn't sure if I should write an entire markdown/mdx section so I decided to start with just file imports.

2024-10-14 08:02 UTC, AriPerkkio commented on docs/tutorialkit.dev/src/content/docs/guides/creating-content.mdx
> +````txt
```suggestion
````md title="content.md"
```

2024-10-14 08:07 UTC, AriPerkkio approved these changes
Looks good to me, thanks @kevinzunigacuellar! 🙌 

In future we can extend the examples to show more features provided by `expressive-code` and Astro, but for now it's good enough to provide links and that one example. 

These changes will be automatically deployed when we release the next version of TutorialKit.

2024-10-14 08:09 UTC, merged